#load data from here
def get_data(batch_size):
    #There are two types of data:
    #1. with randomly sized images (denomination M)
    #2. with images of size (512x512) (dednominationC)
    
    #TODO these sets are to be generated by MATLAB
    #training set
    M_tr = [] #arbitrarily sized images
    C_tr = [] #(512x512) images

    #validation set
    M_val = [] #arbitrarily sized images
    C_val = [] #(512x512) images

    #testing set
    M_test = [] #arbitrarily sized images
    C_test = [] #(512x512) images

    return (M_tr, C_tr, M_val, C_val, M_test, C_test)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               